
https://api.conceitho.com/api/protheus/ctt/api/login/61499545363


###

https://api.conceitho.com/api/protheus/ctt/api/montagem/?{000001,01}


###
https://api.conceitho.com/api/protheus/ctt//api/grava/{Teste}
