swagger: "2.0"
info:
  description: "Serviço REST para retornar informacoes do Portal Pesquisa Satisfação CTT"
  version: "v1.0"
  title: "CTT"
  termsOfService: ""
host: "api.conceitho.com/api/protheus/ctt"
basePath: "/"
schemes:
- "https"
- "http"
paths:
  /api/grava:
    post:
      summary: ""
      description: "Grava dados pesquisa de satisfação preenchida pelo aluno"
      operationId: "0"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters: 
        - in: body
          name: param
          description: Dados a serem gravados
          schema:
            $ref: '#/definitions/body_pd4'
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Bad Request"
        "404":
          description: "Not found"
  /api/login/{cpf}:
    get:
      summary: ""
      description: "validação do login pelo cpf"
      operationId: "1"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "path"
        name: "cpf"
        type: "string"
        description: ""
        required: true
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Bad Request"
        "404":
          description: "Not found"
  /api/montagem/?{turma},{periodo}:
    get:
      summary: ""
      description: "Montagem lista de cursos a partir de um cpf"
      operationId: "2"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "path"
        name: "turma"
        type: "string"
        description: "Turma para montagem"
        required: true
      - in: "path"
        name: "periodo"
        type: "string"
        description: "Periodo para montagem"
        required: true
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Bad Request"
        "404":
          description: "Not found"
definitions:
  body_pd4:
      type: object
      properties:
        PD4_ALUNO:
          type: string
        PD4_TURMA:
          type: string
        PD4_PERIO:
          type: string
        PD4_PROF:
          type: string
        PD4_PESQ:
          type: string
        PD4_DTCURS:
          type: string
        respostas:
          type: array
          items:
            type: object
            properties:
              PD4_ITEM:
                type: string
              PD4_FINALI:
                type: string
              PD4_DEPTO:
                type: string
              PD4_ASSUNT:
                type: string
              PD4_PONTUA:
                type: string
              PD4_RESPOS:
                type: string
              PD4_EQUIV:
                type: string